# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescategorylink',
            name='pce',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
