# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuw', '0003_rescategorylink_pce'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescategorylink',
            name='order',
            field=models.PositiveSmallIntegerField(default=32767),
        ),
    ]
